---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: weather-bot
  name: weather-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      run: weather-bot
  template:
    metadata:
      labels:
        run: weather-bot
        visualize: "true"
    spec:
      containers:
        - name: weather-bot
          image: arthurstrokov/weather-bot:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: spring.mvc.servlet.path
              value: /weather-bot
            - name: BOT-NAME
              valueFrom:
                secretKeyRef:
                  name: weather-bot-secret
                  key: BOT-NAME
            - name: BOT-TOKEN
              valueFrom:
                secretKeyRef:
                  name: weather-bot-secret
                  key: BOT-TOKEN
            - name: BOT-CHAT-ID
              valueFrom:
                secretKeyRef:
                  name: weather-bot-secret
                  key: BOT-CHAT-ID
            - name: OPEN-API-KEY
              valueFrom:
                secretKeyRef:
                  name: weather-bot-secret
                  key: OPEN-API-KEY
            - name: BASE-URL
              valueFrom:
                secretKeyRef:
                  name: weather-bot-secret
                  key: BASE-URL
            - name: SERVER-PORT
              value: "8080"
            - name: EUREKA-DEFAULT-ZONE
              value: "http://192.168.59.101:30001/eureka"
            - name: EUREKA-INSTANCE-HOSTNAME
              value: weather-bot
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: weather-bot
  name: weather-bot
  annotations:
    haproxy.org/check: "enabled"
    haproxy.org/forwarded-for: "enabled"
    haproxy.org/load-balance: "roundrobin"
    haproxy.org/path-rewrite: /
spec:
  selector:
    run: weather-bot
  ports:
    - name: weather-bot-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
