spring:
  main:
    banner-mode: off
  application:
    name: weather-bot
  profiles:
    active: dev

logging:
  level:
    org:
      springframework:
        web: INFO
        boot: INFO
      hibernate: ERROR
    com.gmail.arthurstrokov.weatherbot: DEBUG
