bot:
  name: ${BOT-NAME}
  token: ${TOKEN}
  chatId: ${CHAT-ID}
open:
  api:
    key: ${OPEN-API-KEY}
    url:
      weather:
        current: ${CURRENT}
        five-day: ${FIVE-DAY}
---
server:
  port: 5000
