spring:
  application:
    name: weather-bot
  profiles:
    active: prod

logging:
  level:
    org:
      springframework:
        web: DEBUG
        boot: DEBUG
      hibernate: ERROR
    com.gmail.arthurstrokov.weatherbot: DEBUG
