bot:
  name: ${BOT-NAME}
  token: ${TOKEN}
  chatId: ${CHAT-ID}
---
open:
  api:
    key: ${OPEN-API-KEY}
    url:
      base-url: ${BASE-URL}
    parameters:
      current: /weather
      forecast: /forecast
      city: Minsk
      mode: json
      units: metric
      lang: en
      cnt: 4
---
server:
  port: 8080
