bot:
  name: ${BOT-NAME}
  token: ${TOKEN}
  chatId: ${CHAT-ID}
---
open:
  api:
    key: ${OPEN-API-KEY}
    url:
      current-day-url: ${CURRENT-DAY-URL}
      five-day-url: ${FIVE-DAY-URL}
    parameters:
      city: Minsk
      mode: json
      units: metric
      cnt: 4
---
server:
  port: 5000
